### ISSUE TITLE
JSON instances not defined for `[GuildMember]`

### ISSUE THREAD

**Issue by chrissound** [aquarial/discord-haskell#102] opened 2022-02-13 14:36 UTC
• No instance for (FromJSON (R.GuildRequest [GuildMember]))
    
I'm getting this error when trying to use `ListGuildMembers`. Perhaps I'm doing something simple wrong or not importing a module?
    
Version: discord-haskell-1.12.0

**Comment by aquarial** [comment] 2022-02-21 21:44
Just saw this again, any updates on what's going on?

**Comment by aquarial** [comment] 2022-03-21 18:58
Here's the full runnable example. I'm closing this issue because I can't reproduce it. If you can figure out what's going on, leave a comment let me know. Open a new issue if you run into anything else.

```haskell
import Discord
import Discord.Types
import UnliftIO (liftIO)
import qualified Data.Text.IO as TIO
import qualified Discord.Requests as R

main :: IO ()
main = do
  tok <- TIO.readFile "./examples/auth-token.secret"
  _ <- runDiscord $ def { discordToken = tok
                        , discordOnStart = startHandler
                        }
  pure ()

startHandler :: DiscordHandler ()
startHandler = do
  v <- restCall $ R.ListGuildMembers
                        111111111111111111  -- REPLACE WITH YOUR GUILD ID
                        (R.GuildMembersTiming Nothing Nothing)
  liftIO $ print v
  stopDiscord
```

**Closed by aquarial** 2022-03-21 18:58 UTC

**Comment by aquarial** [comment] 2022-03-28 15:45
Oh haha, figured this one out. What a trip. A minor issue with the library:

I can reproduce the issue with the code you provided. An interesting note is that it affects all the requests:

```haskell
startHandler :: DiscordHandler ()
startHandler = do
  -- CreateMessage :: ChannelId -> T.Text -> ChannelRequest Message
  v <- restCall $ R.CreateMessage 111111111111111111  -- REPLACE WITH YOUR GUILD ID
  stopDiscord
```

produces 

```
examples/gateway.hs:18:8: warning: [-Wdeferred-type-errors]
    • No instance for (FromJSON (R.ChannelRequest Message))
        arising from a use of ‘restCall’
    • In a stmt of a 'do' block:
        v <- restCall $ R.CreateMessage 111111111111111111
```

---------------------------------

Due to currying, that code is passing a `T.Text -> ChannelRequest Message` into `restCall`, which has type:

```haskell
restCall :: (FromJSON a, Request (r a)) => r a -> DiscordHandler (Either RestCallErrorCode a)
restCall r = do [...]
```

The first argument to `restCall` is a generic `r a`, that's restricted by type classes `FromJSON` and `Request`. 

Haskell types are curried too, so the type `T.Text -> ChannelRequest Message` can be written as `(-> T.Text) ChannelRequest Message`. For example looking at ghci we can get some typeclass instances for `(->)`:

```
~> :info (->)
type (->) :: * -> * -> *
data (->) a b
        -- Defined in ‘ghc-prim-0.6.1:GHC.Prim’
infixr -1 ->
instance Applicative ((->) r) -- Defined in ‘GHC.Base’
instance Functor ((->) r) -- Defined in ‘GHC.Base’
```

--------------------------------------------

So `restCall` takes in a `(-> T.Text) (ChannelRequest Message)` where `r = (-> T.Text)` and `a = ChannelRequest Message` and  itchecks the typeclasses `(FromJSON a, Request (r a))` one by one. The first one fails, leading to the confusing error message. Flipping the typeclass restrictions around (`restCall :: (Request (r a), FromJSON a)` leads to a better error message:

```
examples/gateway.hs:18:8: warning: [-Wdeferred-type-errors]
    • No instance for (Discord.Internal.Rest.Prelude.Request
                         (Data.Text.Internal.Text -> R.ChannelRequest Message))
        arising from a use of ‘restCall’
        (maybe you haven't applied a function to enough arguments?)
```

Funny story of haskell types. 

----------------------------

`restCall` takes in such a generic type to let me split up the `Requests` into multiple files. It also would allow someone using the library to define their own ADT that implements `Request` and be able to plug it into the library API.
